### ISSUE TITLE
ray.tune.error.TuneError: ('Trials did not complete', [SACTrainerCustom_modulation_rl_env_6b2a2_00000])

### ISSUE THREAD

**Issue by zhuozhizhong** [robot-learning-freiburg/mobile-rl#4]
I used the Docker images you provided, but when I run 
```
cd catkin_ws_tiago 
source devel/setup.bash
python src/modulation_rl/scripts/main_ray.py --load_best_defaults --num_gpus 0.08 --num_workers 8 --num_cpus_per_worker 0.1 --num_envs_per_worker 1 --num_gpus_per_worker 0 --ray_verbosity 2 --training_intensity 0.1 --load_best_defaults --vis_env
```
occurs
```
(pid=903) 2024-12-05 11:24:34,223	ERROR worker.py:428 -- Exception raised in creation task: The actor died because of an error raised in its creation task, ray::WandbSACTrainer.__init__() (pid=903, ip=172.17.0.3)
(pid=903)   File "/root/catkin_ws_tiago/src/modulation_rl/scripts/modulation/myray/ray_wandb.py", line 195, in __init__
(pid=903)     _init(self, SACTrainerCustom, config, env, logger_creator)
(pid=903)   File "/root/catkin_ws_tiago/src/modulation_rl/scripts/modulation/myray/ray_wandb.py", line 168, in _init
(pid=903)     parent_class.__init__(self, nonwandb_config, env, logger_creator)
(pid=903)   File "/opt/conda/lib/python3.7/site-packages/ray/rllib/agents/trainer_template.py", line 136, in __init__
(pid=903)     Trainer.__init__(self, config, env, logger_creator)
(pid=903)   File "/opt/conda/lib/python3.7/site-packages/ray/rllib/agents/trainer.py", line 592, in __init__
(pid=903)     super().__init__(config, logger_creator)
(pid=903)   File "/opt/conda/lib/python3.7/site-packages/ray/tune/trainable.py", line 103, in __init__
(pid=903)     self.setup(copy.deepcopy(self.config))
(pid=903)   File "/opt/conda/lib/python3.7/site-packages/ray/rllib/agents/trainer_template.py", line 146, in setup
(pid=903)     super().setup(config)
(pid=903)   File "/opt/conda/lib/python3.7/site-packages/ray/rllib/agents/trainer.py", line 739, in setup
(pid=903)     self._init(self.config, self.env_creator)
(pid=903)   File "/opt/conda/lib/python3.7/site-packages/ray/rllib/agents/trainer_template.py", line 175, in _init
(pid=903)     num_workers=self.config["num_workers"])
(pid=903)   File "/opt/conda/lib/python3.7/site-packages/ray/rllib/agents/trainer.py", line 827, in _make_workers
(pid=903)     logdir=self.logdir)
(pid=903)   File "/opt/conda/lib/python3.7/site-packages/ray/rllib/evaluation/worker_set.py", line 111, in __init__
(pid=903)     spaces=spaces,
(pid=903)   File "/opt/conda/lib/python3.7/site-packages/ray/rllib/evaluation/worker_set.py", line 440, in _make_worker
(pid=903)     spaces=spaces,
(pid=903)   File "/opt/conda/lib/python3.7/site-packages/ray/rllib/evaluation/rollout_worker.py", line 584, in __init__
(pid=903)     seed=seed)
(pid=903)   File "/opt/conda/lib/python3.7/site-packages/ray/rllib/evaluation/rollout_worker.py", line 1376, in _build_policy_map
(pid=903)     conf, merged_conf)
(pid=903)   File "/opt/conda/lib/python3.7/site-packages/ray/rllib/policy/policy_map.py", line 137, in create_policy
(pid=903)     merged_config)
(pid=903)   File "/opt/conda/lib/python3.7/site-packages/ray/rllib/policy/policy_template.py", line 267, in __init__
(pid=903)     get_batch_divisibility_req=get_batch_divisibility_req,
(pid=903)   File "/opt/conda/lib/python3.7/site-packages/ray/rllib/policy/torch_policy.py", line 215, in __init__
(pid=903)     self._optimizers = force_list(self.optimizer())
(pid=903)   File "/opt/conda/lib/python3.7/site-packages/ray/rllib/policy/policy_template.py", line 359, in optimizer
(pid=903)     optimizers = optimizer_fn(self, self.config)
(pid=903)   File "/root/catkin_ws_tiago/src/modulation_rl/scripts/modulation/myray/custom_sac.py", line 484, in optimizer_fn_fixed
(pid=903)     policy.actor_optim = get_adam(params=policy.model.policy_variables(), lr=config["optimization"]["actor_learning_rate"])
(pid=903)   File "/root/catkin_ws_tiago/src/modulation_rl/scripts/modulation/myray/custom_sac.py", line 483, in get_adam
(pid=903)     return torch.optim.Adam(params=params, lr=lr, eps=eps)
(pid=903)   File "/opt/conda/lib/python3.7/site-packages/torch/optim/adam.py", line 81, in __init__
(pid=903)     super(Adam, self).__init__(params, defaults)
(pid=903)   File "/opt/conda/lib/python3.7/site-packages/torch/optim/optimizer.py", line 54, in __init__
(pid=903)     self.add_param_group(param_group)
(pid=903)   File "/opt/conda/lib/python3.7/site-packages/torch/optim/optimizer.py", line 269, in add_param_group
(pid=903)     raise ValueError("can't optimize a non-leaf Tensor")
(pid=903) ValueError: can't optimize a non-leaf Tensor
Traceback (most recent call last):
  File "src/modulation_rl/scripts/main_ray.py", line 299, in <module>
    main()
  File "src/modulation_rl/scripts/main_ray.py", line 290, in main
    num_samples=1,
  File "/opt/conda/lib/python3.7/site-packages/ray/tune/tune.py", line 555, in run
    raise TuneError("Trials did not complete", incomplete_trials)
ray.tune.error.TuneError: ('Trials did not complete', [SACTrainerCustom_modulation_rl_env_6b2a2_00000])
```
The issue also occurs in the catkin_ws_pr2 working directory.

Could you give me some help?

**Comment by dHonerkamp** [comment]
Thanks for raising this. I'm afraid I'm not around until after Christmas to check this in detail. But this ma
ight be related to an issue with the pytorch installation. You could try checking if pytorch can correctly run with cuda & the gpu is accessible within docker

**Comment by zhuozhizhong** [comment]
> Thanks for raising this. I'm afraid I'm not around until after Christmas to check this in detail. But this ma ight be related to an issue with the pytorch installation. You could try checking if pytorch can correctly run with cuda & the gpu is accessible within docker

Thank you for your response amidst your busy schedule. I would like to provide some descriptions to better pinpoint the issue.
I used the image your provide, this issue shouldn't related to the version of pytorch. 
```nvidia-smi``` is ok.
Sun Dec  8 10:21:04 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.183.01             Driver Version: 535.183.01   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 4080 ...    Off | 00000000:01:00.0 Off |                  N/A |
| N/A   49C    P0              N/A / 150W |      9MiB / 12282MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
+---------------------------------------------------------------------------------------+

checking  torch and cuda are also avaliable()
```
>>> torch.cuda.is_available()
True

(base) root@25ea7ca5449f:~/catkin_ws_pr2# nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2020 NVIDIA Corporation
Built on Mon_Oct_12_20:09:46_PDT_2020
Cuda compilation tools, release 11.1, V11.1.105
Build cuda_11.1.TC455_06.29190527_0
```
the question above also comes with SACTrainerCustom initial  failed,I think it should be relate to the  SAC network parameter,but I don't know how to fixed it.
```
2024-12-06 17:27:39,694	ERROR trial_runner.py:773 -- Trial SACTrainerCustom_modulation_rl_env_532b0_00000: Error processing event.
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/ray/tune/trial_runner.py", line 739, in _process_trial
    results = self.trial_executor.fetch_result(trial)
  File "/opt/conda/lib/python3.7/site-packages/ray/tune/ray_trial_executor.py", line 746, in fetch_result
    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)
  File "/opt/conda/lib/python3.7/site-packages/ray/_private/client_mode_hook.py", line 82, in wrapper
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/ray/worker.py", line 1623, in get
    raise value
ray.exceptions.RayActorError: The actor died because of an error raised in its creation task, ray::WandbSACTrainer.__init__() (pid=25546, ip=172.17.0.2)
  File "/home/czny/catkin_ws_pr2/src/modulation_rl/scripts/modulation/myray/ray_wandb.py", line 195, in __init__
    _init(self, SACTrainerCustom, config, env, logger_creator)
  File "/home/czny/catkin_ws_pr2/src/modulation_rl/scripts/modulation/myray/ray_wandb.py", line 168, in _init
    parent_class.__init__(self, nonwandb_config, env, logger_creator)
  File "/opt/conda/lib/python3.7/site-packages/ray/rllib/agents/trainer_template.py", line 136, in __init__
    Trainer.__init__(self, config, env, logger_creator)
  File "/opt/conda/lib/python3.7/site-packages/ray/rllib/agents/trainer.py", line 592, in __init__
    super().__init__(config, logger_creator)
  File "/opt/conda/lib/python3.7/site-packages/ray/tune/trainable.py", line 103, in __init__
    self.setup(copy.deepcopy(self.config))
  File "/opt/conda/lib/python3.7/site-packages/ray/rllib/agents/trainer_template.py", line 146, in setup
    super().setup(config)
  File "/opt/conda/lib/python3.7/site-packages/ray/rllib/agents/trainer.py", line 739, in setup
    self._init(self.config, self.env_creator)
  File "/opt/conda/lib/python3.7/site-packages/ray/rllib/agents/trainer_template.py", line 175, in _init
    num_workers=self.config["num_workers"])
  File "/opt/conda/lib/python3.7/site-packages/ray/rllib/agents/trainer.py", line 827, in _make_workers
    logdir=self.logdir)
  File "/opt/conda/lib/python3.7/site-packages/ray/rllib/evaluation/worker_set.py", line 111, in __init__
    spaces=spaces,
  File "/opt/conda/lib/python3.7/site-packages/ray/rllib/evaluation/worker_set.py", line 440, in _make_worker
    spaces=spaces,
  File "/opt/conda/lib/python3.7/site-packages/ray/rllib/evaluation/rollout_worker.py", line 584, in __init__
    seed=seed)
  File "/opt/conda/lib/python3.7/site-packages/ray/rllib/evaluation/rollout_worker.py", line 1376, in _build_policy_map
    conf, merged_conf)
  File "/opt/conda/lib/python3.7/site-packages/ray/rllib/policy/policy_map.py", line 137, in create_policy
    merged_config)
  File "/opt/conda/lib/python3.7/site-packages/ray/rllib/policy/policy_template.py", line 267, in __init__
    get_batch_divisibility_req=get_batch_divisibility_req,
  File "/opt/conda/lib/python3.7/site-packages/ray/rllib/policy/torch_policy.py", line 215, in __init__
    self._optimizers = force_list(self.optimizer())
  File "/opt/conda/lib/python3.7/site-packages/ray/rllib/policy/policy_template.py", line 359, in optimizer
    optimizers = optimizer_fn(self, self.config)
  File "/home/czny/catkin_ws_pr2/src/modulation_rl/scripts/modulation/myray/custom_sac.py", line 484, in optimizer_fn_fixed
    policy.actor_optim = get_adam(params=policy.model.policy_variables(), lr=config["optimization"]["actor_learning_rate"])
  File "/home/czny/catkin_ws_pr2/src/modulation_rl/scripts/modulation/myray/custom_sac.py", line 483, in get_adam
    return torch.optim.Adam(params=params, lr=lr, eps=eps)
  File "/opt/conda/lib/python3.7/site-packages/torch/optim/adam.py", line 137, in __init__
    super(Adam, self).__init__(params, defaults)
  File "/opt/conda/lib/python3.7/site-packages/torch/optim/optimizer.py", line 66, in __init__
    self.add_param_group(param_group)
  File "/opt/conda/lib/python3.7/site-packages/torch/optim/optimizer.py", line 326, in add_param_group
    raise ValueError("can't optimize a non-leaf Tensor")
ValueError: can't optimize a non-leaf Tensor
```
  Thank you again for your assistance !!

**Comment by zhuozhizhong** [comment]
I resolved the issue by setting require_grad to false for all non-leaf node parameters before passing them into the Adam optimizer, and then setting it to true after passing them in.So I close this issue,thank you so much!

**Comment by dHonerkamp** [comment]
A bit late, but I've just come across the actual underlying issue. Please change this line 
`class LocalDoubleMapCNN(jit.ScriptModule):` to `class LocalDoubleMapCNN(nn.Module):` to fix the issue properly
